version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-dev
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb
    networks:
      - dev

networks:
  dev:
    driver: bridge