version: '3'
services:
  sam:
    build: .
    container_name: sam
    ports:
      - "3000:3000"
    networks: 
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./prod/data:/usr/share/elasticsearch/data
      - ./prod/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - esnet

networks:
  esnet: