version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./dev/data:/usr/share/elasticsearch/data
      - ./dev/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - dev

networks:
  dev: 
    driver: bridge